phraseapp:
  access_token: 193b1cb74df9b522e06166c3dc17d5a7055ff9e17bf5ae93c8a97cf3b97a9780 # only pull access
  project_id: 44c4823aea4c479fd3d5f3feaffecd04 #Part-up webapp
  file_format: simple_json
  push:
    sources:
    - file: 'app/i18n/emails.<locale_name>.i18n.json'
      params:
        file_format: simple_json
    - file: 'app/i18n/errors.<locale_name>.i18n.json'
      params:
        file_format: simple_json
    - file: 'app/i18n/notification.<locale_name>.i18n.json'
      params:
        file_format: simple_json
# feature keys: uncomment this block and change filename
#    - file: 'app/i18n/notification.<locale_name>.i18n.json'
#      params:
#        file_format: simple_json
  pull:
    targets:
    - file: 'app/i18n/phraseapp.<locale_name>.i18n.json'
      params:
        file_format: simple_json